-- MySQL Script generated by MySQL Workbench
-- Sun Dec 26 22:46:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `map` (
     `id` BIGINT NOT NULL AUTO_INCREMENT,
     `name` VARCHAR(50) NOT NULL,
     `min_x` INT NOT NULL,
     `min_y` INT NOT NULL,
     `min_z` INT NOT NULL,
     `max_x` INT NOT NULL,
     `max_y` INT NOT NULL,
     `max_z` INT NOT NULL,
     `spawn_x` DECIMAL(9,2) NOT NULL,
     `spawn_y` DECIMAL(9,2) NOT NULL,
     `spawn_z` DECIMAL(9,2) NOT NULL,
     `spawn_yaw` DECIMAL(3,2) NOT NULL,
     `spawn_pitch` DECIMAL(3,2) NOT NULL,
     `world` CHAR(36) NOT NULL,
     PRIMARY KEY (`id`),
     UNIQUE INDEX (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scores` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `player` CHAR(36) NOT NULL,
    `map` BIGINT NOT NULL,
    `time` BIGINT NOT NULL,
    `run_at` TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `Scores_map_map_id` (`map` ASC) VISIBLE,
    CONSTRAINT `Scores_map_map_id`
        FOREIGN KEY (`map`)
            REFERENCES `map` (`id`)
            ON DELETE SET NULL
            ON UPDATE CASCADE);

-- -----------------------------------------------------
-- View `player_highscores`
-- -----------------------------------------------------
CREATE  OR REPLACE VIEW `player_highscores` AS SELECT `player`,`map` , max(`time`) from  `scores` GROUP BY (`player`,`map`);

-- -----------------------------------------------------
-- View `highscores`
-- -----------------------------------------------------
CREATE  OR REPLACE VIEW `highscores` AS SELECT map,max(time) from scores group by map;

